### PR TITLE
Locking and Unlocking of cells

### PR DESCRIPTION
**Pull request by grantfayvor**
Implemented unlocking of cells in a particular column after protecting a worksheet

### CODE REVIEW

**Comment by nakshay** [comment]
are these changes merged ?

**Comment by grantfayvor** [comment]
@nakshay
No, the changes have not been merged.

**Comment by nakshay** [comment]
> @nakshay
> No, the changes have not been merged. cell level control is their pro offering.

And I don't think it will be ever merged.
[here](
image
)

**Comment by nakshay** [comment]
> @nakshay
> No, the changes have not been merged.

And I don't think it will be ever merged.
[here](
image
)

**Pull request closed without merging**
