### PR TITLE
Supporting skipping hidden columns and rows in sheet_to_json

### PR DESCRIPTION
**Pull request by geniejhang**
Simple copy and paste from sheet_to_csv to support skipping hidden columns and rows in sheet_to_json function.

### CODE REVIEW

**Comment by geniejhang** [comment]
Looks like no one is interested :)

**Comment by arnonrdp** [comment]
I can't understand why this is not merged yet.

**Comment by geniejhang** [comment]
@SheetJSDev @arnonrdp Me, neither.

**Comment by geniejhang** [comment]
Latest commit is for bug fix

**Comment by reviewher** [comment]
This PR would close #1280

**Comment by reviewher** [comment]
[0270784](https://github.com/SheetJS/sheetjs/commit/02707848ad3fa7713db4d7864cb80f4616d0b360)

**Pull request closed without merging**
