### PR TITLE
#1087 Add File Separator to ParsingOptions for DSV files

### PR DESCRIPTION
**Pull request by louisjrdev**

### CODE REVIEW

**Comment by louisjacksonrees** [comment]
#1087 This is a PR with the change @SheetJSDev mentioned in this issue

**Comment by louisjacksonrees** [comment]
@SheetJSDev when will this get merged?

**Comment by louisjacksonrees** [comment]
@garrettluu I have just seen a potential issue with this before squashing and I have made updates to solve, just that it needed a check for the custom separator to ensure if one is provided it is processed as a dsv file.

**Comment by mustakim-m2sys** [comment]
@SheetJSDev, when it will be merged in Master?

**Comment by reviewher** [comment]
9e9e4bc

**Pull request closed without merging**
