### PR TITLE
fix date/time rounding issue

### PR DESCRIPTION
**Pull request by scottysseus**
See: #2560

- Improved rounding to account for minutes, hours, etc.
- Added tests for rounding dates/times

### CODE REVIEW

**Comment by SheetJSDev** [comment]
The tests predictably failed on old node versions since they did not support ES6 destructuring.

Did you test against the examples provided by @snoopyjc in https://github.com/SheetJS/sheetjs/issues/2560#issuecomment-1062838050 ?

**Comment by scottysseus** [comment]
@SheetJSDev I would like to get this change merged if there aren't any other issues and you think it's appropriate. Is there anything else I need to do?

**Comment by SheetJSDev** [comment]
Nothing else on your end.  There are some logistical issues we are figuring out regarding date handling.

Ideally, 0.19.0 resolves the outstanding date processing problems which requires both the SSF formatting library and the main file processing library to agree on date code interpretation.

**Comment by MrToadie** [comment]
Thanks for all your work!

**Comment by scottysseus** [comment]
Are there any updates on this? At a quick glance, I'm not able to reproduce this here: https://oss.sheetjs.com/ssf/

but want to make sure this has been fixed and what version it's been fixed in

**Pull request closed without merging**
