### PR TITLE
Fix types used by table_to_book()

### PR DESCRIPTION
**Pull request by michaelmarziani**
This fix allows naming the sheet and using other writing options.

### CODE REVIEW

**Comment by michaelmarziani** [comment]
History of this PR:

I wrote this code in React:

```typescript
const handleExportToExcel = () => {
  const table = document.getElementById('data-table');
  var workBook = XLSX.utils.table_to_book(table, { sheet: "Sheet JS" });
  return XLSX.writeFile(workBook, 'SheetJSTableExport.xlsx');
};
```

TypeScript gave an error:
_Argument of type '{ sheet: string; }' is not assignable to parameter of type 'Table2SheetOpts'.
  Object literal may only specify known properties, and 'sheet' does not exist in type 'Table2SheetOpts'.ts(2345)_

I noticed in the code that the `WritingOptions` interface extends `CommonOptions` and has sheet declared inside it. When I changed `CommonOptions` to `WritingOptions` in the interface declaration for `Table2SheetOpts`, I no longer get this TS error and the function works as expected for my use case.

**Comment by SheetJSDev** [comment]
The other writing options are not supported in `table_to_book` or `table_to_sheet`.  Can you instead introduce another interface `SheetOption`?  Then `Table2SheetOpts` and `WritingOptions` should extend `SheetOption`

**Comment by michaelmarziani** [comment]
I can do that. Thanks for the suggestion.

**Comment by michaelmarziani** [comment]
@SheetJSDev I believe I have done as you requested. Please let me know how it looks.

**Comment by michaelmarziani** [comment]
@SheetJSDev I just wanted to follow up on this PR, please let me know if it needs anything else at your convenience.

**Comment by michaelmarziani** [comment]
@SheetJSDev Thank you!

**Pull request merged**
