### PR TITLE
fix issue #2460

### PR DESCRIPTION
**Pull request by giuliohome**
See the [issue](https://github.com/SheetJS/sheetjs/issues/2460) for more details

### CODE REVIEW

**Comment by giuliohome** [comment]
Let me try to see if the issue can be fixed with option `defval: null` in sheet_to_json and without this PR...
A moment, I'll be back, thanks

**Comment by giuliohome** [comment]
Issue and **PR closed** as per my [comment](https://github.com/SheetJS/sheetjs/issues/2460#issuecomment-977960516)

**Comment by SeniorChiefABLEUnit** [comment]
I am broke, no money, yet 3.6 million offer in Google Calendar. What in the
hell, do you want from me. WHAT? WHAT!

**Comment by giuliohome** [comment]
Reopened to introduce new option `keeporder: true`
I will squash the 2 commits into one

**Comment by giuliohome** [comment]
I'll redo the PR to avoid the rebase failure...

**Pull request closed without merging**
