### PR TITLE
fix: missing PRN in xlsx.mini

### PR DESCRIPTION
**Pull request by chenxeed**
# Issue

https://github.com/SheetJS/sheetjs/issues/1760

# Description

Based on my investigation, it seems like the function `read_prn` in the mini is missing `PRN` when it tries to read a string of CSV file.

My proposed solution is to add the `PRN` declaration as part of the `mini` build, which exists in the `bits/40_harb.js`.

### CODE REVIEW

**Comment by chenxeed** [comment]
@SheetJSDev I have no written unit test in this changes, but I have tested the changes in my local application and the CSV works.

test import svg

**Comment by chenxeed** [comment]
Poke @SheetJSDev again 🙇 it would be great to have this settled for the next release, so we can use `xlsx.mini` in our application ☕

**Comment by chenxeed** [comment]
Hi @SheetJSDev @srijonsaha may I have an update or response for the PR?

If there's anything missing from the PR, please let me know to improve.

I'm waiting for this patch before I can use `xlsx.mini` in my production project.

Thanks!

**Comment by SheetJSDev** [comment]
@garrettluu can you take a peek?

**Comment by chenxeed** [comment]
Thanks @garrettluu for the response and review. I've squashed the commit. Look forward to the update 👍

**Comment by chenxeed** [comment]
Hi @garrettluu @SheetJSDev I've made the requested changes. Please confirm if this is fine. Look forward to the release! 🙇

**Pull request merged**
